### ISSUE TITLE
Failed overflow-checker assertion in C++ mode.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#351]
An assertion in IntegerOverflowChecker fails when compiling in C++ mode:

```
$ cat a.cpp && smack a.cpp --clang-options="-x c++ -std=c++14"

#include <smack.h>

int main() {
	return 0;
}
SMACK program verifier version 1.9.0
Assertion failed: (co != NULL && "Function __SMACK_check_overflow should be present."), function runOnModule, file /Users/mje/Code/smack/lib/smack/IntegerOverflowChecker.cpp, line 113.
Stack dump:
0.	Program arguments: llvm2bpl /Users/mje/Code/smack/b-gxo6nc.bc -bpl /Users/mje/Code/smack/a-p5MCD_.bpl -warnings -source-loc-syms -entry-points main -mem-mod-impls 
1.	Running pass 'Checked integer arithmetic intrinsics' on module '/Users/mje/Code/smack/b-gxo6nc.bc'.
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 769, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 285, in frontend
    return frontends()[lang](args)
  File "/usr/local/bin/../share/smack/top.py", line 362, in clang_plusplus_frontend
    default_link_bc_files(compile_command, args)
  File "/usr/local/bin/../share/smack/top.py", line 448, in default_link_bc_files
    llvm_to_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 499, in llvm_to_bpl
    try_command(cmd, console=True)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: Assertion failed: (co != NULL && "Function __SMACK_check_overflow should be present."), function runOnModule, file /Users/mje/Code/smack/lib/smack/IntegerOverflowChecker.cpp, line 113.
Stack dump:
0.	Program arguments: llvm2bpl /Users/mje/Code/smack/b-gxo6nc.bc -bpl /Users/mje/Code/smack/a-p5MCD_.bpl -warnings -source-loc-syms -entry-points main -mem-mod-impls 
1.	Running pass 'Checked integer arithmetic intrinsics' on module '/Users/mje/Code/smack/b-gxo6nc.bc'.
```

This is a simplified version of michael-emmi/ctverif#2.

**Comment by niekbouman** [comment]
Hi Michael (and/or others),

I managed to get rid of this error by adding a missing function declaration in `smack.h`:
```cpp
void __SMACK_check_overflow(int);
```

Now I am facing another issue, related to
```cpp
smack_value_t __SMACK_value()
```
whose declaration I have (as a hack) changed into 
```cpp
smack_value_t __SMACK_value(int)
```
since C++ does not support C-style functions with unspecified number of arguments.

Now I get an error in `SmackRep.cpp`, namely the `Unexpected argument type` error at line 406 of `SmackRep.cpp`...

**Comment by michael-emmi** [comment]
Hi @niekbouman the issue of the `__SMACK_value` API for C++ code is independent from the overflow -checking code, so let’s please raise it as a separate issue.

**Comment by niekbouman** [comment]
Good idea, I've added it as [issue 353](https://github.com/smackers/smack/issues/353).

**Comment by niekbouman** [comment]
I've opened a new issue for this `exit` related problem; see [359](https://github.com/smackers/smack/issues/359)

**Comment by michael-emmi** [comment]
Shouldn’t we just add the following declaration to `<smack.h>`?
```C
void __SMACK_check_overflow(int);
```

**Comment by zvonimir** [comment]
Yes, I agree we should add `__SMACK_check_overflow` declaration to `smack.h`.
