### ISSUE TITLE
Invalid Boogie code generated from C++ code

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#352]
Compiling even the most trivial C++ code ends up generating invalid Boogie code:

```
$ cat a.cpp && smack a.cpp

#include <smack.h>

int main() {
	return 0;
}
SMACK program verifier version 1.9.0
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 775, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 644, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: /Users/mje/Code/smack/a-sIwrVH.bpl(286,12): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1422,25): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1423,25): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1424,25): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1425,25): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1443,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1444,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1445,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1446,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1447,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1448,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1449,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1450,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1451,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1452,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1453,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1454,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1455,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1456,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1457,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1458,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1459,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1460,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1461,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1462,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1463,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1464,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1465,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1466,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1467,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1468,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1469,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1470,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1471,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1472,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1473,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1474,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1475,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1476,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1477,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1478,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1479,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1480,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1481,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1482,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1483,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1484,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1485,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1486,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1487,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1488,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1489,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1490,29): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1491,32): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1492,32): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1493,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1494,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1495,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1496,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1497,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1498,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1499,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1500,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1501,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1502,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1503,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1504,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1505,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1506,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1507,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1508,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1509,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1510,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1511,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1512,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1513,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1514,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1515,32): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1516,32): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1517,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1518,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1519,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1520,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1521,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1522,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1523,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1524,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1525,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1526,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1527,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1528,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1529,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1530,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1531,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1532,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1533,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1534,31): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1535,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1536,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1537,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1538,30): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1539,34): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1540,32): Error: undeclared type: rmode
/Users/mje/Code/smack/a-sIwrVH.bpl(1733,12): Error: undeclared identifier: RNE
104 name resolution errors in /Users/mje/Code/smack/a-sIwrVH.bpl

Unhandled Exception:
cba.Util.InvalidProg: Cannot resolve /Users/mje/Code/smack/a-sIwrVH.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x0003e] in <0412ab90f0144af5ad2b73412c1bb9d9>:0 
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00001] in <7f6818aab805460b8e0b8e5b1c932599>:0 
  at cba.Driver.run (System.String[] args) [0x00051] in <7f6818aab805460b8e0b8e5b1c932599>:0 
  at cba.Driver.Main (System.String[] args) [0x00067] in <7f6818aab805460b8e0b8e5b1c932599>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: cba.Util.InvalidProg: Cannot resolve /Users/mje/Code/smack/a-sIwrVH.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x0003e] in <0412ab90f0144af5ad2b73412c1bb9d9>:0 
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00001] in <7f6818aab805460b8e0b8e5b1c932599>:0 
  at cba.Driver.run (System.String[] args) [0x00051] in <7f6818aab805460b8e0b8e5b1c932599>:0 
  at cba.Driver.Main (System.String[] args) [0x00067] in <7f6818aab805460b8e0b8e5b1c932599>:0 

```

**Comment by zvonimir** [comment]
I think you have to refresh your installations of Boogie and Corral. I suspect you have an older version that does not support `rmode`.

**Comment by zvonimir** [comment]
I thought more about this, and it is a good opportunity to make sure that no Boogie code that uses interpreted floats is generated when `--float` command line option is not present. I am working on that right now. You should still probably update Boogie/Corral.

**Comment by michael-emmi** [comment]
Yes, that is indeed the problem. I was not aware of these new features in Boogie.

**Comment by michael-emmi** [comment]
Oopse I closed before seeing your latest comment; feel free to reopen.
