### ISSUE TITLE
Error: undeclared type: i256

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#401]
Hello,

I am on the hook to leverage a LLVM IR level model checker to check some pieces of IR code compiled from non C/C++ language. 

I tried to work with some sample code and then start to feed `smack` with my test cases. In my test case `256-bit` integers are commonly used. So current I got the following issue:

````
➜  smack git:(master) ✗ smack --unroll=10 test1.ll
SMACK program verifier version 1.9.3
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 618, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 487, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: /home/vagrant/smack/a-hjMGkj.bpl(60,16): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(135,11): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(136,11): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(142,11): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(143,11): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(144,11): Error: undeclared type: i256
/home/vagrant/smack/a-hjMGkj.bpl(205,15): Error: undeclared type: i256
7 name resolution errors in /home/vagrant/smack/a-hjMGkj.bpl

Unhandled Exception:
cba.Util.InvalidProg: Cannot resolve /home/vagrant/smack/a-hjMGkj.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x00033] in <2038bdfc9ae8413dadd6bd75b7c2f026>:0
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00000] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.run (System.String[] args) [0x00046] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.Main (System.String[] args) [0x0005a] in <81d6c722dfa84867b46a4bab6b9f816f>:0
[ERROR] FATAL UNHANDLED EXCEPTION: cba.Util.InvalidProg: Cannot resolve /home/vagrant/smack/a-hjMGkj.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x00033] in <2038bdfc9ae8413dadd6bd75b7c2f026>:0
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00000] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.run (System.String[] args) [0x00046] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.Main (System.String[] args) [0x0005a] in <81d6c722dfa84867b46a4bab6b9f816f>:0
````

Could anyone shed some lights on this issue? Is it because certain support of 256-bit integers is missing? Any suggestion would be appreciated very much.

**Comment by zvonimir** [comment]
Thanks for reporting this. I know how to fix the problem, but we might have to do another larger update before I go ahead and do this. I'll keep you posted.

**Comment by ireneGP** [comment]
Thank you @zvonimir !  Another quick question, is there any "information flow checker" module in Smack? Something like a "taint analysis" module.

Sorry if it was more proper to open a separate issue to inquire this, I will proceed accordingly. Thank you.

**Comment by ireneGP** [comment]
@zvonimir  Thank you so much! I appreciate your prompt support. It seems the `256-bit` issue is gone, but I then got another issue as follows:

````
llvm2bpl: /home/vagrant/smack/lib/smack/SmackRep.cpp:734: const smack::Expr *smack::SmackRep::ptrArith(const llvm::Value *, std::vector<std::pair<llvm::Value *, llvm::Type *> >): Assertion `ci->getBitWidth() <= 64 && "Unsupported index bitwidth"' failed.
0  libLLVM-3.9.so.1 0x00007f1aa5994fe8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 56
1  libLLVM-3.9.so.1 0x00007f1aa599315e llvm::sys::RunSignalHandlers() + 62
2  libLLVM-3.9.so.1 0x00007f1aa59932ac
3  libpthread.so.0  0x00007f1aa4ad4390
4  libc.so.6        0x00007f1aa3c73428 gsignal + 56
5  libc.so.6        0x00007f1aa3c7502a abort + 362
6  libc.so.6        0x00007f1aa3c6bbd7
7  libc.so.6        0x00007f1aa3c6bc82
8  llvm2bpl         0x00000000004b36fb smack::SmackRep::ptrArith(llvm::Value const*, std::vector<std::pair<llvm::Value*, llvm::Type*>, std::allocator<std::pair<llvm::Value*, llvm::Type*> > >) + 507
9  llvm2bpl         0x00000000004b0fce smack::SmackRep::ptrArith(llvm::GetElementPtrInst const*) + 238
10 llvm2bpl         0x0000000000506e67 smack::SmackInstGenerator::visitGetElementPtrInst(llvm::GetElementPtrInst&) + 87
11 llvm2bpl         0x0000000000489448
12 llvm2bpl         0x0000000000488b1b
13 llvm2bpl         0x00000000004887b2
14 llvm2bpl         0x0000000000488712
15 llvm2bpl         0x00000000004886b2
16 llvm2bpl         0x0000000000484ad2
17 llvm2bpl         0x0000000000483ba1 smack::SmackModuleGenerator::generateProgram(llvm::Module&) + 1953
18 llvm2bpl         0x00000000004833ed smack::SmackModuleGenerator::runOnModule(llvm::Module&) + 29
19 libLLVM-3.9.so.1 0x00007f1aa5a4f6df llvm::legacy::PassManagerImpl::run(llvm::Module&) + 783
20 llvm2bpl         0x000000000047620d main + 3069
21 libc.so.6        0x00007f1aa3c5e830 __libc_start_main + 240
22 llvm2bpl         0x00000000004745e9 _start + 41
Stack dump:
0.      Program arguments: llvm2bpl /home/vagrant/smack/b-PZ9zQa.bc -bpl /home/vagrant/smack/a-0evUCf.bpl -warnings -source-loc-syms -entry-points main -mem-mod-impls
1.      Running pass 'SMACK generator pass' on module '/home/vagrant/smack/b-PZ9zQa.bc'.
````

I will do some "delta-debuggin" to see which part of my LLVM Ir cause the issue. In the meanwhile, may I ask if you happen to some idea about this issue? Thanks a lot!

**Comment by zvonimir** [comment]
Ok, I think I know how to fix this, but please create a separate issue first.

**Comment by ireneGP** [comment]
@zvonimir  Did that. https://github.com/smackers/smack/issues/402 Thank you so much for the support!
