### ISSUE TITLE
undeclared type: i160

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#404]
Hello Smackers!

Thank you so much for the continues support. 

I tried to work with some sample code and then start to feed smack with my test cases. In my test case 256-bit and 160-bit integers are commonly used. So current I got the following issue:

````
SMACK program verifier version 1.9.3
warning: collapsing DSA node
unable to merge call-site arguments with parameters to function realloc
in function:
  array.extend
at instruction:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
at value:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
node:
  VOID: H


warning: collapsing DSA node
unable to merge call-site arguments with parameters to function realloc
in function:
  array.extend
at instruction:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
at value:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
node:
  VOID: H


warning: collapsing DSA node
unable to merge call-site arguments with parameters to function realloc
in function:
  array.extend
at instruction:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
at value:
  %data = load i8*, i8** %dataPtr, !verifier.code !21
node:
  VOID: H


warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 618, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 487, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: /home/vagrant/smack/a-bLxBc7.bpl(295,32): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(296,15): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(494,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(495,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(509,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(510,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(515,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(516,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(525,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(526,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(533,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(534,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(539,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(540,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(543,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(544,12): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(568,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(569,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(574,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(575,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(580,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(581,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(583,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(584,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(600,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(601,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(608,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(609,13): Error: undeclared type: i160

/home/vagrant/smack/a-bLxBc7.bpl(764,13): Error: undeclared type: i160
/home/vagrant/smack/a-bLxBc7.bpl(853,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(859,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(913,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(919,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(929,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(935,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1008,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1014,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1027,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1033,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1045,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1051,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1063,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1069,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1073,10): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1083,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1163,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1169,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1182,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1188,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1196,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1202,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1208,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1212,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1233,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1239,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1276,11): Error: use of undeclared function: $trunc.i256.i160
/home/vagrant/smack/a-bLxBc7.bpl(1282,10): Error: use of undeclared function: $store.i160
/home/vagrant/smack/a-bLxBc7.bpl(1335,11): Error: use of undeclared function: $trunc.i256.i160

98 name resolution errors in /home/vagrant/smack/a-bLxBc7.bpl

Unhandled Exception:
cba.Util.InvalidProg: Cannot resolve /home/vagrant/smack/a-bLxBc7.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x00033] in <2038bdfc9ae8413dadd6bd75b7c2f026>:0
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00000] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.run (System.String[] args) [0x00046] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.Main (System.String[] args) [0x0005a] in <81d6c722dfa84867b46a4bab6b9f816f>:0
[ERROR] FATAL UNHANDLED EXCEPTION: cba.Util.InvalidProg: Cannot resolve /home/vagrant/smack/a-bLxBc7.bpl
  at cba.Util.BoogieUtil.ReadAndOnlyResolve (System.String filename) [0x00033] in <2038bdfc9ae8413dadd6bd75b7c2f026>:0
  at cba.Driver.GetInputProgram (cba.Configs config) [0x00000] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.run (System.String[] args) [0x00046] in <81d6c722dfa84867b46a4bab6b9f816f>:0
  at cba.Driver.Main (System.String[] args) [0x0005a] in <81d6c722dfa84867b46a4bab6b9f816f>:0

````

**Comment by ireneGP** [comment]
@zvonimir  posted! Hope this would be an easy fix as well ;-)

**Comment by ireneGP** [comment]
So I tried to add `160`, following how the `i256` is fixed. Then the model checking works. 

But I still got the `warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
`. Just wondering whether this is an issue.

**Comment by zvonimir** [comment]
Done. We have a more general fix in the pipeline, but hopefully this will do it for now.

**Comment by zvonimir** [comment]
No, this warning is not an issue. It is a detailed warning showing that quantifiers will be introduced.

**Comment by ireneGP** [comment]
I see. Thank you! @zvonimir
