### ISSUE TITLE
undefined method `callers'

### ISSUE THREAD

**Issue by defoye** [smackers/smack#409]

**Comment by defoye** [comment]
No idea what this means.  I hope you can help me.  I am trying mod pow functions from open ssl and libgcrypt and receive this error:

```
/home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/analysis/call_graph_construction.rb:18:in `block in run!': undefined method `callers' for nil:NilClass (NoMethodError)
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:160:in `yield'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:160:in `enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:164:in `block in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:114:in `block in each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bpl/analysis/call_graph_construction.rb:12:in `run!'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:159:in `block (3 levels) in <top (required)>'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam/prelude.rb:135:in `timed'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:158:in `block (2 levels) in <top (required)>'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:156:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:156:in `block in <top (required)>'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:155:in `each'
	from /home/vagrant/verifying-constant-time/tools/bam-bam-boogieman/lib/bam.rb:155:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/verifying-constant-time/bin/../tools/bam-bam-boogieman//bin/bam:4:in `<main>'
```

**Comment by michael-emmi** [comment]
This error is in ct-verif or Bam; it has nothing to do with Smack.

I suggest checking out the latest version of Bam and filing the issue there if the problem persists: https://github.com/michael-emmi/bam-bam-boogieman
