### ISSUE TITLE
Check command line argument ranges

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#431]
It seems SMACK has the following behavior,

```
vagrant@vagrant:~/smack$ smack test/basic/loop.c --time-limit=0
SMACK program verifier version 1.9.3
SMACK found no errors with unroll bound 1.
vagrant@vagrant:~/smack$ smack test/basic/loop.c --time-limit=-1
SMACK program verifier version 1.9.3
SMACK timed out.
```
I think ideally we want to give an error message for the latter case.

**Comment by shaobo-he** [comment]
Not sure if we should take care of this case too.

```
vagrant@vagrant:~/smack$ smack test/basic/loop.c --max-violations=1000000000000000000000000000000000000000000000
SMACK program verifier version 1.9.3
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 612, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 481, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: 
Unhandled Exception:
System.OverflowException: Value was either too large or too small for an Int32.
  at System.Number.ParseInt32 (System.ReadOnlySpan`1[T] s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x0003f] in <b0fbce3aded24cd69a2794df353ebd0a>:0 
  at System.Int32.Parse (System.String s) [0x00016] in <b0fbce3aded24cd69a2794df353ebd0a>:0 
  at cba.Configs.parseFlag (System.String flag) [0x0037b] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Configs.parseCommandLine (System.String[] args) [0x000b7] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Driver.run (System.String[] args) [0x00006] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Driver.Main (System.String[] args) [0x0005a] in <38f34cee706e44d3b325031dd5a75d61>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.OverflowException: Value was either too large or too small for an Int32.
  at System.Number.ParseInt32 (System.ReadOnlySpan`1[T] s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) [0x0003f] in <b0fbce3aded24cd69a2794df353ebd0a>:0 
  at System.Int32.Parse (System.String s) [0x00016] in <b0fbce3aded24cd69a2794df353ebd0a>:0 
  at cba.Configs.parseFlag (System.String flag) [0x0037b] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Configs.parseCommandLine (System.String[] args) [0x000b7] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Driver.run (System.String[] args) [0x00006] in <38f34cee706e44d3b325031dd5a75d61>:0 
  at cba.Driver.Main (System.String[] args) [0x0005a] in <38f34cee706e44d3b325031dd5a75d61>:0 
```

**Comment by shaobo-he** [comment]
Closed because these corner cases are hard to hit.
