### ISSUE TITLE
errors on handle gcc atomic built-in functions

### ISSUE THREAD

**Issue by muyaview** [smackers/smack#456]
llvm2bpl can't handle atomic built-in functions (‘atomicrmw’ instruction in llvm IR). The functions are not generated in boogie codes. 
Like below example:
```c
int main()
{
    int i = 0;

    __sync_fetch_and_add(&i, 1);
    __sync_fetch_and_sub(&i, 1);
    __sync_fetch_and_or(&i, 1);
    __sync_fetch_and_and(&i, 1);
    __sync_fetch_and_xor(&i, 1);
    __sync_fetch_and_nand(&i, 1);

    return i;
}
```
‘atomicrmw’ instructions are generated correctly in llvm IR. However no corresponding functions can be found in bpl file. Below is the error returned by smack:
```
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 629, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 498, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: test.bpl(160,32): Error: use of undeclared function: $add
test.bpl(164,32): Error: use of undeclared function: $sub
test.bpl(168,32): Error: use of undeclared function: $or
test.bpl(172,32): Error: use of undeclared function: $and
test.bpl(176,32): Error: use of undeclared function: $xor
test.bpl(180,32): Error: use of undeclared function: $nand
6 name resolution errors in test.bpl
```

**Comment by zvonimir** [comment]
Good catch, thanks! I just fixed this. Note that you'll have to enable bit-precise reasoning with `--bit-precise` if you would like for SMACK to model bit-vector operations precisely.
