### ISSUE TITLE
`smackgen.py` fails when input file is llvm bitcode

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#48]
The following crashes `smackgen.py` due to the `clangOutput` variable only being defined when a `.c` file is given as input.
````
$ smackgen.py simple.bc -o simple.bpl
Traceback (most recent call last):
  File "/usr/local/bin/smackgen.py", line 117, in <module>
    bpl, options, clangOutput = smackGenerate(sys.argv)
  File "/usr/local/bin/smackgen.py", line 108, in smackGenerate
    return bpl, options, clangOutput
UnboundLocalError: local variable 'clangOutput' referenced before assignment

**Comment by zvonimir** [comment]
Mike, could you check if this is now working for you? I haven't managed to reproduce this issue, and so I suspect it got fixed, in which case we should close it.

**Comment by michael-emmi** [comment]
No longer reproducible.
