### ISSUE TITLE
Invariants on loops with expressions

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#524]
```
% cat loop_with_expr.c && echo -- && smack loop_with_expr.c
#include <smack.h>
#include <smack-contracts.h>

void foo(int i) {
    while (i && 1)
        invariant(1);
}
--
SMACK program verifier version 2.4.0
0  llvm2bpl                 0x0000000101e3cb8e llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
 1  llvm2bpl                 0x0000000101e3cfb8 SignalHandler(int) + 180
 2  libsystem_platform.dylib 0x00007fff699acb5d _sigtramp + 29
 3  llvm2bpl                 0x0000000100868819 std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<llvm::Loop const*, std::__1::vector<llvm::BasicBlock*, std::__1::allocator<llvm::BasicBlock*> > >, void*>, std::__1::__tree_node_destructor<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<llvm::Loop const*, std::__1::vector<llvm::BasicBlock*, std::__1::allocator<llvm::BasicBlock*> > >, void*> > > >::~unique_ptr() + 25
 4  llvm2bpl                 0x000000010086b9d9 llvm::Value::materialized_users() + 25
 5  llvm2bpl                 0x0000000100862882 llvm::Value::users() + 34
 6  llvm2bpl                 0x0000000100861903 smack::ExtractContracts::runOnModule(llvm::Module&) + 2595
 7  llvm2bpl                 0x0000000101d6a1fd llvm::legacy::PassManagerImpl::run(llvm::Module&) + 593
 8  llvm2bpl                 0x00000001007c96c5 main + 4181
 9  libdyld.dylib            0x00007fff697c13d5 start + 1
 Stack dump:
 0.     Program arguments: llvm2bpl /Users/emmmi/Code/smack/b-j5v5f336.bc -bpl /Users/emmmi/Code/smack/a-rgnoo26x.bpl -warn-type unsound -colored-warnings -source-loc-syms -entry-points main -mem-mod-impls -llvm-assumes=none 
 1.     Running pass 'Extract Contracts' on module '/Users/emmmi/Code/smack/b-j5v5f336.bc'.
 Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 679, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 335, in frontend
    return link_bc_files(bitcodes,libs,args)
  File "/usr/local/bin/../share/smack/frontend.py", line 307, in link_bc_files
    llvm_to_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 361, in llvm_to_bpl
    try_command(cmd, console=True)
  File "/usr/local/bin/../share/smack/utils.py", line 67, in try_command
    raise Exception("segmentation fault")
Exception: segmentation fault

**Comment by michael-emmi** [comment]
^ @danielsn

**Comment by danielsn** [comment]
Thanks
