### ISSUE TITLE
Error building SMACK from source on older versions of Ubuntu >18.04

### ISSUE THREAD

**Issue by feliperodri** [smackers/smack#727]
I'm trying to build SMACK from source on Ubuntu 16.04.7 LTS using the `bin/build.sh` script, but I'm getting the following error:
```console
-- Build files have been written to: /home/ubuntu/smack/build
[12/63] Building CXX object CMakeFiles/sma...kTranslator.dir/lib/smack/DSAWrapper.cpp.o
FAILED: /usr/bin/c++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -O3 -fPIC -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -g -MMD -MT CMakeFiles/smackTranslator.dir/lib/smack/DSAWrapper.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/DSAWrapper.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/DSAWrapper.cpp.o -c ../lib/smack/DSAWrapper.cpp
In file included from ../sea-dsa/include/seadsa/CallSite.hh:12:0,
                 from ../sea-dsa/include/seadsa/BottomUp.hh:9,
                 from ../sea-dsa/include/seadsa/Global.hh:9,
                 from ../sea-dsa/include/seadsa/DsaAnalysis.hh:9,
                 from ../include/smack/DSAWrapper.h:13,
                 from ../lib/smack/DSAWrapper.cpp:7:
../sea-dsa/include/seadsa/Graph.hh: In member function ‘constexpr std::tuple<unsigned int, seadsa::FieldType> seadsa::Field::asTuple() const’:
../sea-dsa/include/seadsa/Graph.hh:301:29: error: converting to ‘std::tuple<unsigned int, seadsa::FieldType>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = unsigned int; _T2 = seadsa::FieldType]’
     return {m_offset, m_type};
                             ^
[12/63] Building CXX object CMakeFiles/smackTranslator.dir/lib/smack/Regions.cpp.o
FAILED: /usr/bin/c++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -O3 -fPIC -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -g -MMD -MT CMakeFiles/smackTranslator.dir/lib/smack/Regions.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/Regions.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/Regions.cpp.o -c ../lib/smack/Regions.cpp
In file included from ../include/smack/Regions.h:7:0,
                 from ../lib/smack/Regions.cpp:4:
../sea-dsa/include/seadsa/Graph.hh: In member function ‘constexpr std::tuple<unsigned int, seadsa::FieldType> seadsa::Field::asTuple() const’:
../sea-dsa/include/seadsa/Graph.hh:301:29: error: converting to ‘std::tuple<unsigned int, seadsa::FieldType>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = unsigned int; _T2 = seadsa::FieldType]’
     return {m_offset, m_type};
                             ^
[12/63] Building CXX object CMakeFiles/sma...r.dir/lib/smack/SmackModuleGenerator.cpp.o
FAILED: /usr/bin/c++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -O3 -fPIC -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -g -MMD -MT CMakeFiles/smackTranslator.dir/lib/smack/SmackModuleGenerator.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/SmackModuleGenerator.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/SmackModuleGenerator.cpp.o -c ../lib/smack/SmackModuleGenerator.cpp
In file included from ../include/smack/Regions.h:7:0,
                 from ../lib/smack/SmackModuleGenerator.cpp:10:
../sea-dsa/include/seadsa/Graph.hh: In member function ‘constexpr std::tuple<unsigned int, seadsa::FieldType> seadsa::Field::asTuple() const’:
../sea-dsa/include/seadsa/Graph.hh:301:29: error: converting to ‘std::tuple<unsigned int, seadsa::FieldType>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = unsigned int; _T2 = seadsa::FieldType]’
     return {m_offset, m_type};
                             ^
[12/63] Building CXX object CMakeFiles/sma...ator.dir/lib/smack/CodifyStaticInits.cpp.o
FAILED: /usr/bin/c++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../include -I../sea-dsa/include -I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -O3 -fPIC -fvisibility-inlines-hidden -Werror=date-time -w -fdiagnostics-color -g -MMD -MT CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -MF CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o.d -o CMakeFiles/smackTranslator.dir/lib/smack/CodifyStaticInits.cpp.o -c ../lib/smack/CodifyStaticInits.cpp
In file included from ../sea-dsa/include/seadsa/CallSite.hh:12:0,
                 from ../sea-dsa/include/seadsa/BottomUp.hh:9,
                 from ../sea-dsa/include/seadsa/Global.hh:9,
                 from ../sea-dsa/include/seadsa/DsaAnalysis.hh:9,
                 from ../include/smack/DSAWrapper.h:13,
                 from ../lib/smack/CodifyStaticInits.cpp:8:
../sea-dsa/include/seadsa/Graph.hh: In member function ‘constexpr std::tuple<unsigned int, seadsa::FieldType> seadsa::Field::asTuple() const’:
../sea-dsa/include/seadsa/Graph.hh:301:29: error: converting to ‘std::tuple<unsigned int, seadsa::FieldType>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = unsigned int; _T2 = seadsa::FieldType]’
     return {m_offset, m_type};
                             ^
[12/63] Building CXX object CMakeFiles/sma...tor.dir/lib/smack/SmackInstGenerator.cpp.o
ninja: build stopped: subcommand failed.
```

I tried to use `-std=c++14` flag or to use `clang`, but neither worked.

I also try these [instructions](https://github.com/smackers/smack/blob/master/docs/installation.md#super-quick-setup-virtual-smack) to get `vsmack`, but the link seems broken. Any advice?

**Comment by zvonimir** [comment]
Thanks for reporting this. I've been looking into it, and so far no luck.
Btw, any chance you could update to a more recent version of Ubuntu?
It's been kind of hard to debug this on 16.04.

**Comment by zvonimir** [comment]
Also, have you maybe tried using our Docker build?

**Comment by feliperodri** [comment]
> Thanks for reporting this. I've been looking into it, and so far no luck.
> Btw, any chance you could update to a more recent version of Ubuntu?
> It's been kind of hard to debug this on 16.04.

Of course, which Ubuntu version works for ya?

**Comment by feliperodri** [comment]
> Also, have you maybe tried using our Docker build?

Nope, but I can give it a try too. Btw, wouldn't be easier just to follow these [instructions](https://github.com/smackers/smack/blob/master/docs/installation.md#super-quick-setup-virtual-smack) and get `vsmack`? Could you fix the link?

I'm trying to evaluate SMACK on C++ programs, is there any documentation (e.g., specific configurations) that I should be aware for that?

**Comment by zvonimir** [comment]
When you run `/bin/build.sh` on Ubuntu 20.04, it should build SMACK without any problems. So I would suggest you give it a try on Ubuntu 20.04.

We haven't really been maintaining `vsmack` for a while since nobody was really using it. I will look either into updating it or discontinuing it.

SMACK has not been extensively used on C++ programs. We do know that dynamic dispatch does not work. If you have C++ programs without dynamic dispatch, then things should work. Do you have any case studies you could send out way?
We would definitely like to work towards improving our C++ support.

**Comment by feliperodri** [comment]
> When you run `/bin/build.sh` on Ubuntu 20.04, it should build SMACK without any problems. So I would suggest you give it a try on Ubuntu 20.04.

I also tried to build on Ubuntu 18.04, but I got the following error:
```console
*** SMACK BUILD: Detected distribution: linux-ubuntu-18.04-x86_64 ***
*** SMACK BUILD: Installing required packages ***
2021-05-01 17:26:13 URL:https://apt.llvm.org/llvm-snapshot.gpg.key [3145/3145] -> "-" [1]
OK
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 28, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```

I'm gonna set up an Ubuntu 20.04 instance and give a try.

**Comment by feliperodri** [comment]
> SMACK has not been extensively used on C++ programs. We do know that dynamic dispatch does not work. If you have C++ programs without dynamic dispatch, then things should work. Do you have any case studies you could send out way?
> We would definitely like to work towards improving our C++ support.

I tried to verify the following C++ program with the command line `smack main.cpp` on Ubuntu 20.04
```cpp
#include <iostream>

// function main begins program execution
int main()
{
   std::cout << "Welcome to C++!\n";

   return 0;   // indicate that program ended successfully

} // end function main
```
I got the following error
```console
SMACK program verifier version 2.7.0
clang: error: no such file or directory: '/usr/local/share/smack/lib/smack.cpp'
clang: error: no input files
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 953, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 689, in frontend
    return link_bc_files(bitcodes, libs, args)
  File "/usr/local/bin/../share/smack/frontend.py", line 474, in link_bc_files
    smack_libs += build_lib(args)
  File "/usr/local/bin/../share/smack/frontend.py", line 446, in cplusplus_build_libs
    bc = compile_to_bc(c, compile_command, args)
  File "/usr/local/bin/../share/smack/frontend.py", line 137, in compile_to_bc
    try_command(compile_command + ['-o', bc, input_file], console=True)
  File "/usr/local/bin/../share/smack/utils.py", line 91, in try_command
    raise Exception(output)
Exception: clang: error: no such file or directory: '/usr/local/share/smack/lib/smack.cpp'
clang: error: no input files
```

Did I mess up something during installation or it is legit bug in SMACK? @zvonimir

**Comment by feliperodri** [comment]
I manually copied everything
```console
cp -R ~/smack/share/smack/lib/* /usr/local/share/smack/lib/.
```
and manually installed Corral. It seems to work now. I get the following message:
```console
$ smack main.cpp
SMACK program verifier version 2.7.0
SMACK found no errors with unroll bound 1.
```

**Comment by feliperodri** [comment]
For the following program
```cpp
#include <iostream>
#include <cassert>

int main()
{
   int *a = NULL;
   *a = 2;
   assert(0);
   return 0;
}
```
I get a false positive
```console
SMACK program verifier version 2.7.0
SMACK found no errors with unroll bound 1.
```
Is there any specific flags I should be using in this case?

**Comment by zvonimir** [comment]
@feliperodri I just pushed fixes to the develop branch that resolve your C++ issues.
